# Generated by Django 5.2.3 on 2025-06-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_token_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [("can_deactivation_user", "Can deactivation user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
