# Generated by Django 5.2.2 on 2025-06-11 18:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 11, 21, 2, 4, 152488), verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
