# Generated by Django 5.2.2 on 2025-06-11 18:04

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_alter_mailing_end_alter_mailing_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 11, 21, 4, 53, 955302), verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
