# Generated by Django 5.2.3 on 2025-06-12 16:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0004_client_owner_mailing_owner_mailingattempt_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 12, 19, 23, 40, 924352), verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
