# Generated by Django 5.2.3 on 2025-06-12 19:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0005_alter_mailing_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 12, 22, 19, 2, 202704), verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
