# Generated by Django 5.2.3 on 2025-06-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0006_alter_mailing_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end",
            field=models.DateTimeField(
                help_text="Укажите дату и время окончания отправки в формате: YYYY-MM-DD HH:MM:SS",
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start",
            field=models.DateTimeField(
                help_text="Укажите дату и время первой отправки в формате: YYYY-MM-DD HH:MM:SS",
                verbose_name="Дата и время первой отправки",
            ),
        ),
    ]
