# Generated by Django 5.2.3 on 2025-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0008_alter_mailing_options_mailing_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите дату и время окончания отправки в формате: YYYY-MM-DD HH:MM:SS",
                null=True,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите дату и время первой отправки в формате: YYYY-MM-DD HH:MM:SS",
                null=True,
                verbose_name="Дата и время первой отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="date",
            field=models.DateTimeField(verbose_name="Дата и время попытки"),
        ),
    ]
